services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.Frontend.Dev
    ports:
      - "5173:5173"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
    restart: always


